pydev debugger: process 25776 is connecting

------------------------
mode: train
Loading data
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/aman/Dropbox/CS6220_Amandeep_Singh/HW2/kmeans.py", line 172, in <module>
    FMNIST_Kmeans(mode=TRAIN)
  File "/Users/aman/Dropbox/CS6220_Amandeep_Singh/HW2/kmeans.py", line 33, in __init__
    self.initialize()
  File "/Users/aman/Dropbox/CS6220_Amandeep_Singh/HW2/kmeans.py", line 49, in initialize
    self.init_vectors()
  File "/Users/aman/Dropbox/CS6220_Amandeep_Singh/HW2/kmeans.py", line 146, in init_vectors
    FMNIST = np.genfromtxt(DATA_DIR + '/fashionmnist/fashion-mnist_' + self.mode + '.csv', delimiter=',')
  File "/Users/aman/.envs/digit_rec/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1883, in genfromtxt
    for (i, conv) in enumerate(converters)]))
  File "/Users/aman/.envs/digit_rec/lib/python2.7/site-packages/numpy/lib/_iotools.py", line 691, in _loose_call
    def _loose_call(self, value):
  File "_pydevd_bundle/pydevd_cython.pyx", line 1025, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__ (_pydevd_bundle/pydevd_cython.c:20043)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_is_thread_alive.py", line 14, in is_thread_alive
    def is_thread_alive(t):
KeyboardInterrupt
